export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";

export const FETCH_FEATURED_ITEMS_REQUEST = "FETCH_FEATURED_ITEMS_REQUEST";
export const FETCH_FEATURED_ITEMS_SUCCESS = "FETCH_FEATURED_ITEMS_SUCCESS";
export const FETCH_FEATURED_ITEMS_FAILURE = "FETCH_FEATURED_ITEMS_FAILURE";

export const FETCH_NEW_ITEMS_REQUEST = "FETCH_NEW_ITEMS_REQUEST";
export const FETCH_NEW_ITEMS_SUCCESS = "FETCH_NEW_ITEMS_SUCCESS";
export const FETCH_NEW_ITEMS_FAILURE = "FETCH_NEW_ITEMS_FAILURE";